name: Release

on:
  push:
    branches: [master]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  typecheck:
    uses: ./.github/workflows/typecheck.yml

  build:
    needs: [lint, test, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm run build

      - uses: EndBug/add-and-commit@v9
        with:
          message: "[BUILD]: update build output"
